# Ex - GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

### Step 3. Assign it to a variable called drinks.

In [2]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv"
df = pd.read_csv(url)

In [15]:
df.describe(include="all")

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
count,193,193.000000,193.000000,193.000000,193.000000,170
unique,193,NaN,NaN,NaN,NaN,5
top,Afghanistan,NaN,NaN,NaN,NaN,AF
freq,1,NaN,NaN,NaN,NaN,53
mean,NaN,106.160622,80.994819,49.450777,4.717098,NaN
std,NaN,101.143103,88.284312,79.697598,3.773298,NaN
min,NaN,0.000000,0.000000,0.000000,0.000000,NaN
25%,NaN,20.000000,4.000000,1.000000,1.300000,NaN
50%,NaN,76.000000,56.000000,8.000000,4.200000,NaN
75%,NaN,188.000000,128.000000,59.000000,7.200000,NaN
max,NaN,376.000000,438.000000,370.000000,14.400000,NaN

### Step 4. Which continent drinks more beer on average?

In [27]:
df.groupby("continent")[["beer_servings"]].mean()

           beer_servings
continent
AF             61.471698
AS             37.045455
EU            193.777778
OC             89.687500
SA            175.083333

### Step 5. For each continent print the statistics for wine consumption.

In [30]:
df.groupby("continent")[["wine_servings"]].describe()

          wine_servings                                                   \
                  count        mean        std  min   25%    50%     75%
continent
AF                 53.0   16.264151  38.846419  0.0   1.0    2.0   13.00
AS                 44.0    9.068182  21.667034  0.0   0.0    1.0    8.00
EU                 45.0  142.222222  97.421738  0.0  59.0  128.0  195.00
OC                 16.0   35.625000  64.555790  0.0   1.0    8.5   23.25
SA                 12.0   62.416667  88.620189  1.0   3.0   12.0   98.50


             max
continent
AF         233.0
AS         123.0
EU         370.0
OC         212.0
SA         221.0

### Step 6. Print the mean alcohol consumption per continent for every column

In [34]:
df.groupby("continent").mean(numeric_only=True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

### Step 7. Print the median alcohol consumption per continent for every column

In [35]:
df.groupby("continent").median(numeric_only=True)

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

### Step 8. Print the mean, min and max values for spirit consumption.
#### This time output a DataFrame

In [ ]:
# Dictionary aggregation
df.groupby("continent").agg(
    {"spirit_servings" : ["mean", "min", "max"],
    #  "wine_servings": ["mean", "min", "max"]
     })

          spirit_servings
                     mean min  max
continent
AF              16.339623   0  152
AS              60.840909   0  326
EU             132.555556   0  373
OC              58.437500   0  254
SA             114.750000  25  302

In [64]:
# Named aggregation
df.groupby("continent").agg(
    spirit_serving_mean = ("spirit_servings", "mean"),
    spirit_serving_min = ("spirit_servings", "min"),
    spirit_serving_max = ("spirit_servings", "max"),
)

           spirit_serving_mean  spirit_serving_min  spirit_serving_max
continent
AF                   16.339623                   0                 152
AS                   60.840909                   0                 326
EU                  132.555556                   0                 373
OC                   58.437500                   0                 254
SA                  114.750000                  25                 302